[client]
showSidebarNavigation = false
toolbarMode="minimal"

[theme]
primaryColor="#3F72AF" #"#FF4B4B"
backgroundColor="#FFFFFF" #"#F9F7F7"
secondaryBackgroundColor="#DBE2EF" #"#F0F2F6"
textColor="#31333F"
font="sans serif"

